name: reactive_ble_windows
description: Windows implementation for the flutter_reactive_ble plugin.
version: 0.0.1
homepage: https://github.com/JRHarrison167/flutter_reactive_ble

environment:
  sdk: ">=2.15.0-268.8.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  reactive_ble_platform_interface: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: flutter_reactive_ble
    platforms:
      windows:
        pluginClass: ReactiveBleWindowsPlugin
